eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
jwt:
  secret: ${JWT_SECRET}

